### ISSUE TITLE
Kaelly as a deamon in Systemsd

### ISSUE THREAD

**Issue by Kaysoro** [Kaysoro/KaellyBot#106]
- daily reboot (5am ?)
- reboot with a superadmin command (no more ssh :o )

**Comment by MadJlzz** [comment]
I configured Kaelly as a daemon on my own server. Here is my systemd service unit that you could use as an example:
```
[Unit]
Description=KaellyBot systemd service.

[Service]
WorkingDirectory=/home/dobot
ExecStart=/usr/bin/java -jar /home/dobot/kaelly.jar
User=dobot

[Install]
WantedBy=multi-user.target
```

Then, simply use `sudo systemctl enable dobot.service` to let systemctl restart the daemon when a reboot occurs.

**Comment by Kaysoro** [comment]
It's done for few months ago, forgot to close this issue, thanks :)
