### ISSUE TITLE
SQL command for superadmin

### ISSUE THREAD

**Issue by Kaysoro** [Kaysoro/KaellyBot#110]
OMG a backdoor is coming

**Comment by S0ngfu** [comment]
Il faudrait limiter la commande au SELECT et interdire tout le reste, non ?

**Comment by Kaysoro** [comment]
Je ne sais pas trop, cette issue me dérange un peu et je me demande si des metrics à côté ne suffirait pas: le besoin sous-jacent était de pouvoir mettre à jour la production sans relancer tout le client mais avec le système de cache en place, ce n'est pas très intéressant

**Comment by Kaysoro** [comment]
Dangerous and useless. Better ways are coming with v2.0.
