### ISSUE TITLE
Dockeriser KaellyBot

### ISSUE THREAD

**Issue by MadJlzz** [Kaysoro/KaellyBot#217]
Salut,

L'idée c'est de containeriser l'app pour éviter aux users de devoir la builder manuellement.
Je peux faire ça sans soucis et l'héberger sur un public registry ;)

**Comment by Kaysoro** [comment]
Hello :)
A vrai dire c'était prévu de dockeriser l'ensemble des éléments de kaellybot; cette version passera en deprecated quand j'aurai fini d'amener toutes les fonctionnalités dans la nouvelle mouture, disponible sur le groupe github/KaellyBot !
Etant donné qu'il y a une base de données SQLite sur cette version, il n'y aura que ça à passer dans le volume, ainsi qu'un fichier application.properties. Mise à part ça, c'est tout !

**Comment by MadJlzz** [comment]
Ce que j'ai en tête:
- build de l'image avec [Jib](https://github.com/GoogleContainerTools/jib/tree/master/jib-maven-plugin). Ton CI sur Travis continuera de fonctionner sans adaptation ;
- on peux publier l'image sur [Docker Hub](https://hub.docker.com/) ;
- pour ta base SQLite je peux aussi te proposer un Compose file pour tout en une ligne de commande.

Besoin d'autre chose ?

**Comment by Kaysoro** [comment]
Non non niquel, et Jib m'intéressait beaucoup pour le projet à côté (sous spring) !
Il faudra que je prépare un script ou un fichier sqlite prêt pour un environnement de base pour que ce soit ok ! Je suis disponible sur discord si jamais tu souhaites échanger autrement :)

**Comment by MadJlzz** [comment]
Super !
Je te laisse créer un compte sur DockerHub où tu préfères que je te laisse pousser l'image quand c'est prêt ?

**Comment by Kaysoro** [comment]
kaellybot/kaellybot pour le répertoire, tu es dans la team de l'organization pour push les images :)
Ces images sont publiques.

**Comment by Kaysoro** [comment]
Done in Kaellybot/kaelly-core
