### ISSUE TITLE
Le script bdd.sqlite.sql n'est pas complet

### ISSUE THREAD

**Issue by MadJlzz** [Kaysoro/KaellyBot#218]
Il semblerait que le serveur plante au démarrage. Cela est lié à des colonnes manquantes dans le script d'init bdd.sqlite.sql.

Il manque la colonne `game` dans la table `Server`.
Il manque la table `Server_Label`.

D'autres peut-être...

**Comment by Kaysoro** [comment]
Hello, oui, comme je le disais dans la précédente fiche, je ne l'ai pas mise à jour, il faut que je le fasse ! Je laisse l'issue ouverte je commiterai prochainement dessus ! :)

**Comment by MadJlzz** [comment]
Vu que je suis en train d'essayer faire tourner le serveur, je peux m'en occuper ? Je suis en train de fix actuellement. Comme tu préfères.
