### ISSUE TITLE
Les almanax ont changés et le bot ne donne plus les bonnes offrandes

### ISSUE THREAD

**Issue by Nokmatt** [Kaysoro/KaellyBot#293]
Bonjour,

Depuis la mise à jour de Dofus du 26/03/2024, le bot ne donne plus les bons dons pour l'almanax. En effet le site https://www.krosmoz.com/fr/almanax a bien été mis à jour aujourd'hui mais le bot donnes les anciennes offrandes quand on execute la commande !almanax .

Une mise à jour du bot est-elle en cours ?

**Comment by Kaysoro** [comment]
Bonjour,
Une mise à jour côté Ankama a eu lieu dans la journée et l'url que tu as donné n'est aujourd'hui plus le moyen que l'on utilise pour récupérer l'almanax : nous passons par l'outil [dofusdu.de](https://docs.dofusdu.de/) qui récupère l'almanax d'une façon différente. J'ai invalidé le cache pour aujourd'hui, les données devraient être les bonnes à présent :)
