### ISSUE TITLE
Le bot semble ne plus fonctionner

### ISSUE THREAD

**Issue by Nokmatt** [Kaysoro/KaellyBot#294]
La commande !almanax ou /about ne fonctionne plus

**Comment by Kaysoro** [comment]
Bonjour Nokmatt, la raison n'est pas propre au bot mais à son hébergement, nous avons ouvert un ticket et nous sommes pour le moment sans réponse...

**Comment by Nokmatt** [comment]
D'accord merci pour l'information :)
