### ISSUE TITLE
!sound doesn't work after a deban

### ISSUE THREAD

**Issue by S0ngfu** [Kaysoro/KaellyBot#61]
After ban/deban or kick from a guild the sound command doesn't work. Other commands are fine.

After a kick, I got out from the vocal channel, invited Kaelly again and tried the sound command. She joined the channel even tho she shouldn't have because I was not in it.

**Comment by Gekyou** [comment]
Same bug here, the bot is constantly in the channel and don't moove

**Comment by Kaysoro** [comment]
Hi, seems to be a bug deeper, in the discord framework. It has to be tested but this is not a priority for now; when it occur, send me a message on discord via the support server and I will reload the bot :)

**Comment by Kaysoro** [comment]
Will be refactored with the new discord wrapper
